### ISSUE TITLE
What subprojects we should add?

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity.org#1]
technical threshold is: a photo, a line of subtitle, at least one link

**Comment by djahnie** [comment]
I'm still absolutely in favor of adding **yucu** for everything regarding the theory or the lifestyle of unconditional sharing. Also, **foodsaving worldwide** is a project on it's own, I mean the networking, the documentation and all the communication to build a global foodsaving movement.
I already wrote stuff for both of these topics.

EDIT: I added these two pages. You okay, with what I did there?
