### ISSUE TITLE
Make page translatable

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity.org#7]
@nicksellen I guess you have some knowledge using crowdin ;)

**Comment by nicksellen** [comment]
Yes :) Things get added into my account, which is not perfect, but I can add other people as managers who have full access (except I am still owner). I will ask them to up my limit again - although they just did it this morning again.

Any feeling about how it compares with transifex though?

**Comment by tiltec** [comment]
Both look and behave nice, I didn't interact much with crowdin yet. Transifex doesn't have built-in github integration.
